# Generated by Django 4.1.2 on 2022-10-06 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['codigo_departamento']},
        ),
    ]
